services:

  postgres:
    image: postgres:17

    container_name: postgres-db

    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0

    container_name: zookeeper

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0

    container_name: kafka

    depends_on:
      - zookeeper

    ports:
      - "9092:9092"

    environment:

      KAFKA_BROKER_ID: 1

      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"

      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"

      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  auth-service:
    build: ./auth-service

    container_name: auth-service

    depends_on:
      - postgres
      - kafka

    ports:
      - "8081:8081"

  patient-service:
    build: ./patient-service

    container_name: patient-service

    depends_on:
      - postgres
      - kafka

    ports:
      - "8082:8082"

  doctor-service:
    build: ./doctor-service

    container_name: doctor-service

    depends_on:
      - postgres
      - kafka

    ports:
      - "8083:8083"

  appointment-service:
    build: ./appointment-service

    container_name: appointment-service

    depends_on:
      - postgres
      - kafka

    ports:
      - "8084:8084"

  ai-service:
    build: ./ai-service

    container_name: ai-service

    ports:
      - "8085:8085"

  prescription-service:
    build: ./prescription-service

    container_name: prescription-service

    depends_on:
      - postgres
      - kafka

    ports:
      - "8086:8086"

medical-record-service:
  build: ./medical-record-service

  container_name: medical-record-service

  depends_on:
    - postgres
    - kafka

  ports:
    - "8087:8087"

lab-service:
  build: ./lab-service

  container_name: lab-service

  depends_on:
    - postgres
    - kafka

  ports:
    - "8088:8088"

notification-service:
  build: ./notification-service

  container_name: notification-service

  depends_on:
    - kafka

  ports:
    - "8089:8089"

file-service:
  build: ./file-service

  container_name: file-service

  depends_on:
    - postgres
    - kafka

  ports:
    - "8090:8090"

payment-service:
  build: ./payment-service

  container_name: payment-service

  depends_on:
    - postgres
    - kafka

  ports:
    - "8091:8091"