spring.application.name=api-gateway

server.port=8080

eureka.client.enabled=false

spring.cloud.discovery.enabled=false

# AUTH SERVICE

spring.cloud.gateway.mvc.routes[0].id=auth-service

spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8081

spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/auth/**

# PATIENT SERVICE

spring.cloud.gateway.mvc.routes[1].id=patient-service

spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8082

spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/patients/**

# DOCTOR SERVICE

spring.cloud.gateway.mvc.routes[2].id=doctor-service

spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8083

spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/doctors/**

spring.cloud.gateway.mvc.routes[3].id=appointment-service

spring.cloud.gateway.mvc.routes[3].uri=http://localhost:8084

spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/appointments/**

spring.cloud.gateway.mvc.routes[4].id=ai-service

spring.cloud.gateway.mvc.routes[4].uri=http://localhost:8085

spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/ai/**
#prescription service

spring.cloud.gateway.mvc.routes[5].id=prescription-service

spring.cloud.gateway.mvc.routes[5].uri=http://localhost:8086

spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/api/prescriptions/**
# medical records
spring.cloud.gateway.mvc.routes[6].id=medical-record-service

spring.cloud.gateway.mvc.routes[6].uri=http://localhost:8087

spring.cloud.gateway.mvc.routes[6].predicates[0]=Path=/api/medical-records/**
#lab service
spring.cloud.gateway.mvc.routes[7].id=lab-service

spring.cloud.gateway.mvc.routes[7].uri=http://localhost:8088

spring.cloud.gateway.mvc.routes[7].predicates[0]=Path=/api/labs/**

#file-service
spring.cloud.gateway.mvc.routes[8].id=file-service

spring.cloud.gateway.mvc.routes[8].uri=http://localhost:8090

spring.cloud.gateway.mvc.routes[8].predicates[0]=Path=/api/files/**
#payment service
spring.cloud.gateway.mvc.routes[9].id=payment-service

spring.cloud.gateway.mvc.routes[9].uri=http://localhost:8091

spring.cloud.gateway.mvc.routes[9].predicates[0]=Path=/api/payments/**