spring.application.name=ai-service

server.port=8092

spring.ai.ollama.base-url=http://localhost:11434

spring.ai.ollama.chat.options.model=llama3.2
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=ai-group

spring.kafka.consumer.auto-offset-reset=earliest

spring.ai.ollama.embedding.options.model=nomic-embed-text

spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true